#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Generated by chatGPT

'''该脚本首先遍历每个子文件夹，并为训练和测试文件夹中的每个子文件夹创建一个对应的子文件夹。
然后，它找到该子文件夹中的所有PNG文件，并随机打乱它们的顺序。
接下来，该脚本计算出该子文件夹中应该用于训练和测试的图像数量，并将前80％的图像复制到用于培
训的子文件夹中，将剩余的图像复制到用于测试的子文件夹中。
这样，你就可以在train文件夹和test文件夹中看到你的随机分配的图像了。'''

import os
import random
import shutil

# 定义常量
DATA_DIR = "../data/capture"
TRAIN_DIR = "../data/train"
TEST_DIR = "../data/test"
TRAIN_PERCENT = 0.8

# 遍历每个子文件夹
for subdir in os.listdir(DATA_DIR):
    if os.path.isdir(os.path.join(DATA_DIR, subdir)):
        # 创建对应的训练和测试子文件夹
        train_subdir = os.path.join(TRAIN_DIR, subdir)
        test_subdir = os.path.join(TEST_DIR, subdir)
        os.makedirs(train_subdir, exist_ok=True)
        os.makedirs(test_subdir, exist_ok=True)

        # 获取所有png图片的文件名
        png_files = [f for f in os.listdir(os.path.join(DATA_DIR, subdir)) if f.endswith(".png")]

        # 打乱文件名的顺序
        random.shuffle(png_files)

        # 计算用于训练和测试的图片数量
        num_train = int(len(png_files) * TRAIN_PERCENT)
        num_test = len(png_files) - num_train

        # 将80%的图片放入训练文件夹，剩余的放入测试文件夹
        for i, filename in enumerate(png_files):
            if i < num_train:
                shutil.move(os.path.join(DATA_DIR, subdir, filename), os.path.join(train_subdir, filename))
            else:
                shutil.move(os.path.join(DATA_DIR, subdir, filename), os.path.join(test_subdir, filename))